---
title: "Data Analysis"
author: "Derek"
date: '2023-03-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(lubridate)
library(zoo)
library(dplyr)
library(astsa)
library(caret)
library(ggplot2)
```


```{r}
Comments = read.csv("Cleaned Comments.csv")
GameInfo = read_excel("Game system requriements.xlsx")
```

```{r}
df <- merge(Comments, GameInfo, by = "Game")
```

```{r}
write.csv(df,"C:/Users/derek/OneDrive - Denison University/D_Q/US/2023 Spring/DA 401\\FinalData.csv", row.names = FALSE)
```

```{r}
df = read.csv("FinalData.csv")
```


```{r}
df <- df %>%
  mutate(month = month(ymd(Release.Date)), year = year(ymd(Release.Date)))

# Calculate season
df <- df %>%
  mutate(Date = case_when(
    month %in% 1:3 ~ paste0(year, ".1"),
    month %in% 4:6 ~ paste0(year, ".2"),
    month %in% 7:9 ~ paste0(year, ".3"),
    month %in% 10:12 ~ paste0(year, ".4")
  ))
```

```{r}
Pdiscomfort <- c(0.006390977,0.007227174,0.011299435,0.007226514,0.003150738)
```

```{r}
tsplot(Pdiscomfort,main = "Percent discomfort comments in the past decades",xaxt="n")
axis(1,at=c(1,2,3,4,5),labels=c("2007.11-2013.8","2015.4-2016.8","2016.9-2017.10","2017.12-2019.8","2019.10-2021.3"))
```





```{r}
wss = data.frame(k=1:15,wss=sapply(1:15, function(k) kmeans(df[,4], k, nstart=10)$tot.withinss))
wss %>%
  ggplot(aes(x=k, y=wss))+
  geom_line()+
  ggtitle("Plot of Within Cluster Sum of Squares")+
  ylab("within cluster Sum of Squares")+
  xlab("k values")
```

```{r}
cluster = kmeans(df$Pdiscomfort, 10)
df$clusters = cluster$cluster

centers <- aggregate(Pdiscomfort ~ clusters, df, mean)

ggplot(df, aes(x = as.factor(clusters), y = Pdiscomfort, color = factor(clusters))) +
  geom_point() +
  geom_point(data = centers, aes(x = as.factor(clusters), y = Pdiscomfort), size = 5, shape = 16, fill = "white") +
  scale_color_discrete(labels = paste0("Cluster ", 1:10))+
  labs(title = "Percent discomfort comments by Cluster", x = "Clusters", y = "Percent of comments that have the keywords")
```

```{r}
dist_mat <- dist(df)

# Apply hierarchical clustering with complete linkage
hc <- hclust(dist_mat, method = "complete")

plot(hc)
```






























